const page = document.body.dataset.page || 'home';
const navItems = [['home','Home','index.html'],['story','Our Story','story.html'],['menu','Menu','menu.html'],['locations','Locations','locations.html'],['gallery','Gallery','gallery.html'],['reviews','Reviews','reviews.html'],['contact','Contact','contact.html']];
const header = document.getElementById('site-header');
if (header) header.innerHTML = `<header class="site-header"><div class="container nav"><a href="index.html" class="brand">Waris Nihari</a><nav class="nav-links" aria-label="Main navigation">${navItems.map(([key,label,href])=>`<a class="${page===key?'active':''}" href="${href}">${label}</a>`).join('')}</nav><div class="nav-actions"><a class="btn btn-secondary nav-menu-link" href="menu.html">Explore menu</a><a class="btn btn-primary nav-order-link" href="checkout.html">Order now <span data-cart-count>0</span></a><button class="mobile-toggle" id="mobileToggle" aria-label="Toggle navigation" aria-expanded="false">Menu</button></div></div><div class="container mobile-nav" id="mobileNav">${navItems.map(([,label,href])=>`<a href="${href}">${label}</a>`).join('')}</div></header>`;
const footer = document.getElementById('site-footer');
if (footer) footer.innerHTML = `<footer class="site-footer"><div class="container footer-inner"><div><div class="brand">Waris Nihari</div><p class="muted">Traditional Pakistani nihari in Lahore.</p><p class="muted">© ${new Date().getFullYear()} Waris Nihari. Concept site.</p></div><div class="footer-links"><a href="story.html">Our Story</a><a href="menu.html">Menu</a><a href="locations.html">Locations</a><a href="gallery.html">Gallery</a><a href="reviews.html">Reviews</a><a href="contact.html">Contact</a></div></div></footer>`;
const toggle=document.getElementById('mobileToggle'), mobileNav=document.getElementById('mobileNav');
if(toggle&&mobileNav) toggle.addEventListener('click',()=>{const open=mobileNav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});
const getCart=()=>JSON.parse(localStorage.getItem('waris-cart')||'[]');
const saveCart=(cart)=>{localStorage.setItem('waris-cart',JSON.stringify(cart));updateCartCount(cart);renderCart(cart);};
const updateCartCount=(cart=getCart())=>document.querySelectorAll('[data-cart-count]').forEach(node=>node.textContent=cart.reduce((sum,item)=>sum+item.quantity,0));
function renderCart(cart=getCart()){const target=document.getElementById('checkout-items');if(!target)return;if(!cart.length){target.innerHTML='<p class="muted">Your order is empty — browse the menu.</p><a class="btn btn-secondary" href="menu.html">Browse menu</a>';return;}target.innerHTML=cart.map((item,index)=>`<div class="cart-row"><div><strong>${item.name}</strong><small>Price pending verification</small></div><span>× ${item.quantity}</span><button class="text-button" data-remove="${index}" type="button">Remove</button></div>`).join('');target.querySelectorAll('[data-remove]').forEach(button=>button.addEventListener('click',()=>{const next=getCart();next.splice(Number(button.dataset.remove),1);saveCart(next);}));}
function productCard(item){const price=item.price===null?'[Add price]':`${item.price} PKR`;return `<article class="product-card"><a class="product-image" href="product.html?id=${item.id}"><img src="${item.image}" alt="${item.name} — editorial image placeholder"><span class="image-note">Editorial image</span></a><div class="product-body"><div class="product-card-head"><h3><a href="product.html?id=${item.id}">${item.name}</a></h3><strong class="price">${price}</strong></div><p>${item.shortDescription}</p><div class="product-actions"><a class="text-link" href="product.html?id=${item.id}">Details →</a>${item.available?`<button class="btn btn-primary btn-mini add-to-cart" data-name="${item.name}" data-id="${item.id}" type="button">Add</button>`:'<span class="tag-small">Unavailable</span>'}</div></div></article>`;}
async function loadMenu(){const target=document.getElementById('menu-catalog');if(!target)return;const data=await fetch('data/menu.json').then(response=>response.json());target.innerHTML=data.menu.map(productCard).join('');bindMenuInteractions(data.menu);}
function bindMenuInteractions(items){document.querySelectorAll('[data-filter]').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(item=>item.classList.remove('active'));tab.classList.add('active');const filter=tab.dataset.filter;document.querySelectorAll('[data-category]').forEach(item=>item.hidden=filter!=='all'&&item.dataset.category!==filter);}));document.querySelectorAll('.add-to-cart').forEach(button=>button.addEventListener('click',()=>{const cart=getCart(),existing=cart.find(item=>item.id===button.dataset.id);if(existing)existing.quantity+=1;else cart.push({id:button.dataset.id,name:button.dataset.name,quantity:1});saveCart(cart);button.textContent='Added';setTimeout(()=>button.textContent='Add',900);}));}
async function loadProduct(){const target=document.getElementById('product-page');if(!target)return;const id=new URLSearchParams(location.search).get('id');const data=await fetch('data/menu.json').then(response=>response.json());const item=data.menu.find(entry=>entry.id===id);if(!item){target.innerHTML='<section class="page-hero"><div class="container empty-state"><h1>Dish not found</h1><a class="btn btn-primary" href="menu.html">Back to menu</a></div></section>';return;}document.title=`${item.name} | Waris Nihari`;target.innerHTML=`<section class="page-hero"><div class="container"><span class="eyebrow">Menu detail</span><h1>${item.name}</h1><p>${item.shortDescription}</p></div></section><section><div class="container product-detail"><div class="detail-image"><img src="${item.image}" alt="${item.name} — editorial image placeholder"><span class="image-note">Editorial photograph — replace with approved restaurant photography.</span></div><div class="detail-copy"><span class="tag-small">${item.category}</span><h2>${item.name}</h2><p>${item.description}</p><div class="detail-facts"><div><span>Price</span><strong>${item.price===null?'[Add price]':`${item.price} PKR`}</strong></div><div><span>Spice</span><strong>${item.spiceLevel}</strong></div><div><span>Allergens</span><strong>${item.allergens}</strong></div></div>${item.available?'<button class="btn btn-primary add-to-cart" data-id="'+item.id+'" data-name="'+item.name+'" type="button">Add to order</button>':'<span class="tag-small">Currently unavailable</span>'}<a class="text-link" href="menu.html">← Back to menu</a></div></div></section>`;target.querySelector('.add-to-cart')?.addEventListener('click',event=>{const cart=getCart(),existing=cart.find(entry=>entry.id===event.currentTarget.dataset.id);if(existing)existing.quantity+=1;else cart.push({id:event.currentTarget.dataset.id,name:event.currentTarget.dataset.name,quantity:1});saveCart(cart);event.currentTarget.textContent='Added to order';});}
const checkoutForm=document.getElementById('checkout-form');
if(checkoutForm)checkoutForm.addEventListener('submit',event=>{event.preventDefault();const message=document.getElementById('checkout-message');message.textContent='Checkout is not active yet. Your information was not submitted and no payment was taken. Connect a real order endpoint and payment provider to enable this flow.';});
updateCartCount();renderCart();loadMenu();loadProduct();
